# Azure DevOps Pipeline for AfvalAlert
trigger:
- main
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'afvalalert-classifier'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build and push
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageName)
        dockerfile: classifier/Dockerfile
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest

- stage: Deploy
  displayName: Deploy to Azure
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy to Azure App Service
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: Deploy to Azure App Service
            inputs:
              appName: $(appName)
              imageName: $(imageName):$(tag)
              azureSubscription: $(azureSubscription)