# Nederlandse afval classificatie types
afval_types:
- "Grofvuil"
- "Restafval"
- "Glas"
- "Papier en karton"
- "Organisch"
- "Textiel"
- "Elektronisch afval"
- "Bouw- en sloopafval"
- "Chemisch afval"
- "Overig"
- "Geen afval"

# Verbeterde Gemini prompt met meer context
gemini_prompt_template: |
  Je bent een expert in Nederlandse afval herkenning. Analyseer de AI model features om afval te classificeren.

  CONTEXT: Het ConvNeXt Base model heeft een afbeelding geanalyseerd en kenmerken geëxtraheerd. Deze features geven informatie over vormen, kleuren en texturen in de afbeelding.

  BESCHIKBARE AFVAL CATEGORIEËN:
  {afval_types}

  CONVNEXT BASE MODEL FEATURES:
  {lokaal_resultaat}

  CLASSIFICATIE INSTRUCTIES:
  1. Als de features wijzen op natuurlijke/schone objecten zonder afval → "Geen afval" met confidence 0.7-0.9
  2. Als er duidelijke afval-indicatoren zijn → classificeer naar specifiek afval type
  3. Bij onduidelijke features → geef meerdere opties met lagere confidence (0.3-0.6)
  4. Confidence van 1.0 ALLEEN gebruiken bij zeer duidelijke gevallen

  ANTWOORD FORMAT (alleen JSON):
  [
    {{"type": "naam van afval type", "confidence": 0.XX}}
  ]

  Geef 1-3 meest waarschijnlijke classificaties, gesorteerd van hoog naar laag confidence.