# Locatie configuratie
gebied:
  naam: "Groningen"
  type: "gemeente"
  land: "Nederland"

# OpenStreetMap configuratie
nominatim:
  baseUrl: "https://nominatim.openstreetmap.org"
  reverseZoom: 18
  searchZoom: 18
  addressdetails: 1
  format: "json"

# Locatie validatie
validatie:
  vereisteVelden:
    - "gemeente"
    - "provincie"
  toegestaneLanden:
    - "Nederland"
    - "Netherlands"
    - "NL"